"""Add constraints and improve foreign keys

Revision ID: 4de4472c38d6
Revises: f6854a4dd3ad
Create Date: 2026-08-06 16:28:53.130949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4de4472c38d6'
down_revision: Union[str, Sequence[str], None] = 'f6854a4dd3ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('projects_name_key'), 'projects', type_='unique')
    op.create_index('idx_project_created_by', 'projects', ['created_by'], unique=False)
    op.create_index('idx_project_region', 'projects', ['region'], unique=False)
    op.create_index(op.f('ix_projects_created_by'), 'projects', ['created_by'], unique=False)
    op.drop_constraint(op.f('projects_created_by_fkey'), 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_sites_project_id'), 'sites', ['project_id'], unique=False)
    op.drop_constraint(op.f('sites_project_id_fkey'), 'sites', type_='foreignkey')
    op.create_foreign_key(None, 'sites', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.drop_constraint(op.f('users_role_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_role_id_fkey'), 'users', 'roles', ['role_id'], ['id'])
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_constraint(None, 'sites', type_='foreignkey')
    op.create_foreign_key(op.f('sites_project_id_fkey'), 'sites', 'projects', ['project_id'], ['id'])
    op.drop_index(op.f('ix_sites_project_id'), table_name='sites')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('projects_created_by_fkey'), 'projects', 'users', ['created_by'], ['id'])
    op.drop_index(op.f('ix_projects_created_by'), table_name='projects')
    op.drop_index('idx_project_region', table_name='projects')
    op.drop_index('idx_project_created_by', table_name='projects')
    op.create_unique_constraint(op.f('projects_name_key'), 'projects', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
