"""add remaining gis enrichment fields

Revision ID: cdd7055ee4fc
Revises: 311deeb2bda4
Create Date: 2026-08-08 07:28:16.731426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdd7055ee4fc'
down_revision: Union[str, Sequence[str], None] = '311deeb2bda4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('water_body_distance', sa.Float(), nullable=True))
    op.add_column('sites', sa.Column('protected_area_distance', sa.Float(), nullable=True))
    op.add_column('sites', sa.Column('land_slope', sa.Float(), nullable=True))
    op.add_column('sites', sa.Column('vegetation_index', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sites', 'vegetation_index')
    op.drop_column('sites', 'land_slope')
    op.drop_column('sites', 'protected_area_distance')
    op.drop_column('sites', 'water_body_distance')
    # ### end Alembic commands ###
