"""add gis fields to site

Revision ID: f6854a4dd3ad
Revises: 13b5b859d029
Create Date: 2026-07-23 14:42:21.479872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6854a4dd3ad'
down_revision: Union[str, Sequence[str], None] = '13b5b859d029'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('region', sa.String(length=150), nullable=True))
    op.add_column('sites', sa.Column('land_area', sa.Float(), nullable=True))
    op.add_column('sites', sa.Column('elevation', sa.Float(), nullable=True))
    op.add_column('sites', sa.Column('existing_infrastructure', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('land_use', sa.String(length=100), nullable=True))
    op.add_column('sites', sa.Column('road_distance', sa.Float(), nullable=True))
    op.add_column('sites', sa.Column('nearest_substation_distance', sa.Float(), nullable=True))
    op.add_column('sites', sa.Column('nearest_transmission_line_distance', sa.Float(), nullable=True))
    op.drop_constraint(op.f('users_role_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_role_id_fkey'), 'users', 'roles', ['role_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('sites', 'nearest_transmission_line_distance')
    op.drop_column('sites', 'nearest_substation_distance')
    op.drop_column('sites', 'road_distance')
    op.drop_column('sites', 'land_use')
    op.drop_column('sites', 'existing_infrastructure')
    op.drop_column('sites', 'elevation')
    op.drop_column('sites', 'land_area')
    op.drop_column('sites', 'region')
    # ### end Alembic commands ###
